-- Vouchly school demonstration database
-- IMPORTANT: This demo intentionally stores the password as entered for classroom
-- demonstration only. Do NOT use this design for a real public authentication system.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vouchers (
  id bigint generated by default as identity primary key,
  restaurant text not null,
  title text not null,
  description text not null,
  discount text not null,
  category text not null,
  accent text not null default '#6d4aff',
  expires_at date not null,
  voucher_code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.claims (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  voucher_id bigint not null references public.vouchers(id) on delete cascade,
  claimed_at timestamptz not null default now(),
  unique(user_id, voucher_id)
);

-- Demo data
insert into public.vouchers
  (restaurant, title, description, discount, category, accent, expires_at, voucher_code)
values
  ('McDonald''s', '₱100 OFF', 'Get ₱100 off your qualifying order.', '₱100 OFF', 'Burgers', '#ffb000', '2026-12-31', 'MCD100-DEMO'),
  ('Jollibee', 'Free Peach Mango Pie', 'Enjoy a free Peach Mango Pie with a qualifying meal.', 'FREE PIE', 'Chicken', '#e53935', '2026-11-30', 'JBL-PIE-DEMO'),
  ('KFC', '20% OFF Bucket Meal', 'Save 20% on selected bucket meals.', '20% OFF', 'Chicken', '#c62828', '2026-12-15', 'KFC20-DEMO'),
  ('Burger King', '₱80 OFF Whopper', 'Take ₱80 off a qualifying Whopper meal.', '₱80 OFF', 'Burgers', '#f4511e', '2026-10-31', 'BK80-DEMO')
on conflict (voucher_code) do nothing;